#!/bin/bash
# A script to make a bootstrap 3 template
# bootstrap3_template - A script to make a bootstrap 3 template
#Use this like this: ./tut_template  > <filename>.html
cat << _EOF_
<?php
    define ("NORMALIZE", "<link href='../css/normalize.css' rel='stylesheet'>");
    define ("BOOTSTRAP", "<link href='../css/bootstrap.min.css' rel='stylesheet'>");
    define ("STYLE", "<link href='../css/style.css' rel='stylesheet'>");
    define("TITLE", "Netbeans and MAMP Setup | David Mendez");
    include('php/head.php');
?>
   <div class='container' id="wrapper">
   <h4>Last Modified: June 7, 2016</h4>
   
   <h1>Page Title</h1>

   <h2>Introduction</h2>
   <p>Introductory statement.</p>

   <h2 id="step1">Step1: </h2>
   <p>This some text explaining some of the steps in step1.</p>

   <h2 id="step2">Step2: </h2>
   <p>This some text explaining some of the steps in step2.</p>   

   <h2 id="step3">Step3: </h2>
   <p>This some text explaining some of the steps in step3.</p>

   <h2 id="step4">Step4: </h2>
   <p>This some text explaining some of the steps in step4.</p>

   <h2 id="step5">Step5: </h2>
   <p>This some text explaining some of the steps in step5.</p>

   <h2 id="step6">Step6: </h2>
   <p>This some text explaining some of the steps in step6.</p>

<?php include('php/footer.php'); ?>
_EOF_

