#!/bin/bash
# A script to make a bootstrap 3 template
# bootstrap3_template - A script to make a bootstrap 3 template
cat << _EOF_
<?php
    define ("NORMALIZE", "<link href='../css/normalize.css' rel='stylesheet'>");
    define ("BOOTSTRAP", "<link href='../css/bootstrap.min.css' rel='stylesheet'>");
    define ("STYLE", "<link href='../css/style.css' rel='stylesheet'>");
    define("TITLE", "Netbeans and MAMP Setup | David Mendez");
    include('php/head.php');
?>
   <div class='container' id="wrapper">


<?php include('php/footer.php'); ?>
_EOF_
echo "Use this like this: make_bootstrap3_template > bootstrap3_template.html"
